#!/usr/bin/env node

var program = require('commander');

program
  .version('0.1.0');

program
  .command('init')
  .description('initialize the database')
  .action(function(env, options) {

  }).on('--help', function() {
    console.log('Example:');
    console.log();
    console.log('  $ contacts init');
  });
